wget http://autoplot.org/wiki/images/matlabInterface.png
wget http://autoplot.org/wiki/images/chickadeeSpectrogram.jpg
wget http://autoplot.org/wiki/images/TimeSeries20190220.jpg
wget http://autoplot.org/wiki/images/vap_inline_events.jpg
wget http://autoplot.org/wiki/images/vap+inline+events.jpg
wget http://autoplot.org/wiki/images/ScriptEditor.jpg
wget http://autoplot.org/wiki/images/20181204_141651.png
wget http://autoplot.org/wiki/images/saveVapEmbed.png
wget http://autoplot.org/wiki/images/jythonScriptHoverLookup.jpg
wget http://autoplot.org/wiki/images/apds.cdf.jpg
wget http://autoplot.org/wiki/images/createPngWalk2018.jpg
wget http://autoplot.org/wiki/images/RunBatch.jpg
wget http://autoplot.org/wiki/images/generation_and_parsing.png
wget http://autoplot.org/wiki/images/template_use_overview.png
wget http://autoplot.org/wiki/images/customRenderer.png
wget http://autoplot.org/wiki/images/Logo96.png
wget http://autoplot.org/wiki/images/Logo128.png
wget http://autoplot.org/wiki/images/CustomRendererVertHist.jpg
wget http://autoplot.org/wiki/images/scripts_2.1_2.png
wget http://autoplot.org/wiki/images/scripts_2.1_1_1.png
wget http://autoplot.org/wiki/images/scripts_2.1_1.png
wget http://autoplot.org/wiki/images/scripts_2.1_0.png
wget http://autoplot.org/wiki/images/Dashup0.jpg
wget http://autoplot.org/wiki/images/qdataset-rank2.jpg
wget http://autoplot.org/wiki/images/qdataset-rank1-v2.jpg
wget http://autoplot.org/wiki/images/qdataset-rank1.jpg
wget http://autoplot.org/wiki/images/autoplotIntroduction.ppt
wget http://autoplot.org/wiki/images/annotation2.png
wget http://autoplot.org/wiki/images/annotation.png
wget http://autoplot.org/wiki/images/annotationProperties.png
wget http://autoplot.org/wiki/images/pngwalk.png
wget http://autoplot.org/wiki/images/menubar.png
wget http://autoplot.org/wiki/images/tabs.png
wget http://autoplot.org/wiki/images/addressbar.png
wget http://autoplot.org/wiki/images/createPngWalk.jpg
wget http://autoplot.org/wiki/images/cdfEditorPanel.jpg
wget http://autoplot.org/wiki/images/product_20140102.png
wget http://autoplot.org/wiki/images/Logo128x128b.png
wget http://autoplot.org/wiki/images/MacLionSecurity.jpg
wget http://autoplot.org/wiki/images/javawsAuth.jpg
wget http://autoplot.org/wiki/images/java5gui.jpg
wget http://autoplot.org/wiki/images/nnSpectrogram.png
wget http://autoplot.org/wiki/images/digital.png
wget http://autoplot.org/wiki/images/custom2.png
wget http://autoplot.org/wiki/images/custom1.png
wget http://autoplot.org/wiki/images/colorScatter.png
wget http://autoplot.org/wiki/images/scatter.png
wget http://autoplot.org/wiki/images/orbitPlot.png
wget http://autoplot.org/wiki/images/pitchAngleDistribution.png
wget http://autoplot.org/wiki/images/imageRenderer.png
wget http://autoplot.org/wiki/images/eventsBar.png
wget http://autoplot.org/wiki/images/hugeScatter.png
wget http://autoplot.org/wiki/images/series.png
wget http://autoplot.org/wiki/images/spectrogram.png
wget http://autoplot.org/wiki/images/dragndrop1.png
wget http://autoplot.org/wiki/images/dragndrop0.png
wget http://autoplot.org/wiki/images/chrome3.png
wget http://autoplot.org/wiki/images/ProxySettings.png
wget http://autoplot.org/wiki/images/badidea.png
wget http://autoplot.org/wiki/images/safari1.png
wget http://autoplot.org/wiki/images/Firefox1.png
wget http://autoplot.org/wiki/images/chrome2.png
wget http://autoplot.org/wiki/images/chrome1.png
wget http://autoplot.org/wiki/images/compile2.png
wget http://autoplot.org/wiki/images/compile.png
wget http://autoplot.org/wiki/images/Image.jpg
wget http://autoplot.org/wiki/images/TimeSeries.jpg
wget http://autoplot.org/wiki/images/Spectrogram.jpg
wget http://autoplot.org/wiki/images/EventsBarFurnaceOn.jpg
wget http://autoplot.org/wiki/images/pitchAngleDistribution.jpg
wget http://autoplot.org/wiki/images/colorScatterPlot.jpg
wget http://autoplot.org/wiki/images/tweakLabelPosition.jpg
wget http://autoplot.org/wiki/images/efficientStackOfThreePlots.png
wget http://autoplot.org/wiki/images/stackOfThreePlots.png
wget http://autoplot.org/wiki/images/clippingLayout.jpg
wget http://autoplot.org/wiki/images/idlMatlabInterface.png
wget http://autoplot.org/wiki/images/ScriptEditor.png
wget http://autoplot.org/wiki/images/TimeSeriesBrowse.swf
wget http://autoplot.org/wiki/images/jydsEditor2.jyds.png
wget http://autoplot.org/wiki/images/jydsEditor.jyds.png
wget http://autoplot.org/wiki/images/cdaweb.png
wget http://autoplot.org/wiki/images/AggregationGUI.jpg
wget http://autoplot.org/wiki/images/manylabels.png
wget http://autoplot.org/wiki/images/layoutdom.png
wget http://autoplot.org/wiki/images/das2ServerEditorPanel.png
wget http://autoplot.org/wiki/images/CDAWebDB.png
wget http://autoplot.org/wiki/images/InsideAutoplot-20110531.ppt
wget http://autoplot.org/wiki/images/InsideAutoplot.ppt
wget http://autoplot.org/wiki/images/WavDataSourceEditorPanelImage.png
wget http://autoplot.org/wiki/images/layout.png
wget http://autoplot.org/wiki/images/logo.svg
wget http://autoplot.org/wiki/images/autoplot.svg
wget http://autoplot.org/wiki/images/agu2010.ppt
wget http://autoplot.org/wiki/images/ascii_data_source_wiki_1.png
wget http://autoplot.org/wiki/images/BGSM.png
wget http://autoplot.org/wiki/images/Bcurtis3Test.vap
wget http://autoplot.org/wiki/images/Bcurtis3Test.png
wget http://autoplot.org/wiki/images/rank2Ascii.swf
wget http://autoplot.org/wiki/images/omni.vap
wget http://autoplot.org/wiki/images/sw_data_20031120.vap
wget http://autoplot.org/wiki/images/sw_data_20031120.png
wget http://autoplot.org/wiki/images/bobsExercise.vap
wget http://autoplot.org/wiki/images/bobsExercise.png
wget http://autoplot.org/wiki/images/thumb_plot_labels.png
wget http://autoplot.org/wiki/images/thumb_nav_basic.png
wget http://autoplot.org/wiki/images/thumb_nav_advanced.png
wget http://autoplot.org/wiki/images/thumb_multi_panel.png
wget http://autoplot.org/wiki/images/thumb_ascii_data.png
wget http://autoplot.org/wiki/images/thumb_aggregation.png
wget http://autoplot.org/wiki/images/muti_panel.swf
wget http://autoplot.org/wiki/images/plot_labels.swf
wget http://autoplot.org/wiki/images/advanced_nav.swf
wget http://autoplot.org/wiki/images/aggregation.swf
wget http://autoplot.org/wiki/images/cdfplot.swf
wget http://autoplot.org/wiki/images/asciiplot.swf
wget http://autoplot.org/wiki/images/Navigation.swf
wget http://autoplot.org/wiki/images/Logo32x32.png
wget http://autoplot.org/wiki/images/fireworks.png
wget http://autoplot.org/wiki/images/HelpZoom.swf
wget http://autoplot.org/wiki/images/tsds-sampex-spectrogram.png
wget http://autoplot.org/wiki/images/tsds-omni-density.png
wget http://autoplot.org/wiki/images/demo005_demo12.png
wget http://autoplot.org/wiki/images/demo005_demo11.png
wget http://autoplot.org/wiki/images/demo005_demo14.png
wget http://autoplot.org/wiki/images/demo005_demo13.png
wget http://autoplot.org/wiki/images/demo005_demo10.png
wget http://autoplot.org/wiki/images/demo005_demo9.png
wget http://autoplot.org/wiki/images/demo005_demo8.png
wget http://autoplot.org/wiki/images/demo005_demo7.png
wget http://autoplot.org/wiki/images/demo005_demo6.png
wget http://autoplot.org/wiki/images/demo005_demo5.png
wget http://autoplot.org/wiki/images/demo005_demo4.png
wget http://autoplot.org/wiki/images/demo3_completions.jpg
wget http://autoplot.org/wiki/images/test005_demo2.png
wget http://autoplot.org/wiki/images/test_005_demo1.png
wget http://autoplot.org/wiki/images/QDataSetRank1Depend0.jpg
wget http://autoplot.org/wiki/images/QDataSetRank1.png
wget http://autoplot.org/wiki/images/dataSourceCompletions.png
wget http://autoplot.org/wiki/images/dataSourceEditorPanel.png
wget http://autoplot.org/wiki/images/Metadata.png
wget http://autoplot.org/wiki/images/browserMetaphor.png
wget http://autoplot.org/wiki/images/nb_build_screen-23.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-22.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-21.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-20.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-19.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-18.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-17.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-16.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-15.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-14.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-13.7.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-13.4.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-13.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-12.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-11.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-10.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-09.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-08.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-07.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-06.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-05.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-04.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-03.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-02.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-01.jpg
wget http://autoplot.org/wiki/images/nb_build_screen-00.jpg
wget http://autoplot.org/wiki/images/TS-1319.pdf
wget http://autoplot.org/wiki/images/Spinner16.gif
wget http://autoplot.org/wiki/images/Agu2008.pdf.zip
wget http://autoplot.org/wiki/images/BrowserMetaphor.png
wget http://autoplot.org/wiki/images/Das2.png
wget http://autoplot.org/wiki/images/AllTabs.png
wget http://autoplot.org/wiki/images/AutoplotAll.jar
wget http://autoplot.org/wiki/images/Jumbojar.jar
wget http://autoplot.org/wiki/images/Autoplot.ppt
wget http://autoplot.org/wiki/images/QDataSet.ppt
wget http://autoplot.org/wiki/images/Dragon.130px.png
wget http://autoplot.org/wiki/images/Ap-local.zip
wget http://autoplot.org/wiki/images/HEO1.xml
wget http://autoplot.org/wiki/images/Autoplot-advanced.png
wget http://autoplot.org/wiki/images/ZoomPanColorbar.swf
wget http://autoplot.org/wiki/images/Addressbar.png
wget http://autoplot.org/wiki/images/Aggregation.swf
wget http://autoplot.org/wiki/images/Ftpcdf.swf
wget http://autoplot.org/wiki/images/Save_as_ascii.swf
wget http://autoplot.org/wiki/images/Zoomscan.swf
wget http://autoplot.org/wiki/images/Autoplot-cdf-metadata.png
wget http://autoplot.org/wiki/images/Autoplot-cdf-variable.png
wget http://autoplot.org/wiki/images/Autoplot-basic.png
wget http://autoplot.org/wiki/images/Autoplot-spase.png
wget http://autoplot.org/wiki/images/Autoplot.png
